[toolchain]

[features]
seeds = false
skip-lint = true
init-if-needed = []

[programs.localnet]
blockchain_solana = "DVzV16mVG9vHdrum9Fx9kGhzRv2GJa2mNnmTWUnKa6st"

[programs.devnet]
blockchain_solana = "DVzV16mVG9vHdrum9Fx9kGhzRv2GJa2mNnmTWUnKa6st"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
